name: MacOS target

on:
  workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: update make
      run: brew install make
    - name: env check
      run: gmake --version && python3 --version
    - name: make
      run: gmake debug
    - name: test output
      run: bin/qrcode -g 3 oagoulart.github.io/rambles/keep-thyself-credible
